// com.iex.api.localc
// Naming convention: https://wiki.openoffice.org/wiki/Documentation/DevGuide/AppendixA/General_Design_Rules

module com {
    module iex {
        module api {
            module localc {
                interface XIex
                {
                  // Identifier (e.g. ticker symbol), item (e.g. tag or series id)
                  any IexPrice( [in] string symbol );
                  // Returns count of keys in a quote
                  any IexQuoteKeyCount();
                  // Returns a key by index
                  any IexQuoteKeyByIndex( [in] long keyindex );
                  // Returns a key value
                  any IexQuoteItem( [in] string symbol, [in] string itemkey );
                  // Returns count of keys in a company
                  any IexCompanyKeyCount();
                  // Returns a key by index
                  any IexCompanyKeyByIndex( [in] long keyindex );
                  // Returns a key value
                  any IexCompanyItem( [in] string symbol, [in] string itemkey );
                  // Returns count of keys in a key stats result
                  any IexKeyStatsKeyCount();
                  // Returns a key by index
                  any IexKeyStatsKeyByIndex( [in] long keyindex );
                  // Returns a key value
                  any IexKeyStatsItem( [in] string symbol, [in] string itemkey );
                  // Returns count of keys in a key stats result
                  any IexDividendsKeyCount();
                  // Returns count of keys in a key stats result
                  any IexDividendsPeriodCount([in] string symbol, [in] string periodrange);
                  // Returns a key by index
                  any IexDividendsKeyByIndex( [in] long keyindex );
                  // Returns a key value
                  any IexDividendsItem( [in] string symbol, [in] string itemkey, [in] long period, [in] string periodrange );
                  // Returns a key value
                  any IexDividendsTTM( [in] string symbol );
                  // Returns count of keys in an earnings result
                  any IexEarningsKeyCount();
                  // Returns a key by index
                  any IexEarningsKeyByIndex( [in] long keyindex );
                  // Returns a key value
                  any IexEarningsItem( [in] string symbol, [in] string itemkey, [in] long period );
                  // Returns a key value
                  any IexHistoricalQuote( [in] string symbol, [in] string fordate );
                };
            };
        };
    };
};
